/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Newspaper(props) {
  const { nodes, materials } = useGLTF('/models/newspaper2.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.np_mid.geometry}
        material={materials['newspaper_page-0001']}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.nplow.geometry}
        material={materials['newspaper_page-0001']}
        position={[-0.13, 0, 0]}
        rotation={[0, 1.43, 0]}
      />
      <mesh
        geometry={nodes.np_top.geometry}
        material={materials['newspaper_page-0001']}
        position={[0.1, 0, 0]}
        rotation={[-Math.PI, 1.53, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload('/models/newspaper2.glb');
